language: android
android:
    components:
        - android-23
        - build-tools-23.0.1
        - platform-tools
        - extra

jdk: oraclejdk7

sudo: false

before_script:
    - chmod +x gradlew

script:
    - ./gradlew assembleDebug --stacktrace

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d7975967d97f7a351e33
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
